package uk.ac.ucl.cs.nterreri.frames;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * JFrame demonstrating registering an actionListener to a JComboBox by
 * instantiating an interface object then overriding its actionPerformed
 * method.
 * 
 * This method uses the static class JOptionPane to generated a popup window
 * upon catching the ActionEvent generated by selecting an item in the JComboBox
 * @author nterreri
 *
 */
class ComboBox extends JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8576235631234031481L;
	private JPanel contentPane;
	private JComboBox<String> comboBox;
	//Not declaring a JOptionPane instance because the method to be invoked is static:
	//private JOptionPane confirmation;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				try {
					ComboBox frame = new ComboBox();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public ComboBox() {
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 450, 300);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		
		comboBox = new JComboBox<String>();
		comboBox.setBounds(155, 116, 138, 24);
		comboBox.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				
				JOptionPane.showMessageDialog(comboBox, "Selected option " + comboBox.getSelectedItem(), 
						"You Selected " + comboBox.getSelectedItem() + "!", JOptionPane.INFORMATION_MESSAGE);
			}
		});
		contentPane.setLayout(null);
		comboBox.setModel(new DefaultComboBoxModel<String>(new String[] {"option1", "option2", "option3", "option4", "option5"}));
		comboBox.setToolTipText(" - options -");
		contentPane.add(comboBox);
		
		
		
	}

}
